#ifndef TETRIS_GAME_SETTINGS_H
#define TETRIS_GAME_SETTINGS_H

#define PLAYFIELD_ROWS 20
#define PLAYFIELD_COLUMNS 10
#define PLAYFIELD_PLACEMENT_ROW 15
#define PLAYFIELD_PLACEMENT_COLUMN 45
#define PLAYFIELD_SIZE (PLAYFIELD_ROWS * PLAYFIELD_COLUMNS)
#define PLAYFIELD_WINDOW_COLUMNS (PLAYFIELD_COLUMNS * 2)

#define PREVIEW_ROWS 4
#define PREVIEW_COLUMNS 6
#define PREVIEW_PLACEMENT_ROW 25
#define PREVIEW_PLACEMENT_COLUMN 70
#define PREVIEW_WINDOW_COLUMNS (PREVIEW_COLUMNS * 2)

#define WINDOW_BORDER 2

#define TETRIMINO_COUNT 7
#define SQUARES_PER_TETRIMINO 4

#define LIGHTBLUE_SPAWNPOINT 4
#define DARKBLUE_SPAWNPOINT 13
#define ORANGE_SPAWNPOINT 13
#define YELLOW_SPAWNPOINT 13
#define GREEN_SPAWNPOINT 13
#define RED_SPAWNPOINT 13
#define MAGENTA_SPAWNPOINT 13

#endif

