#ifndef TETRIS_GAME_SETTINGS_H
#define TETRIS_GAME_SETTINGS_H

#define TARGET_FPS 144
#define MICROSECONDS_PER_SECOND 1000000
#define TARGET_FRAME_TIME (MICROSECONDS_PER_SECOND / TARGET_FPS)
#define NANOSECONDS_PER_MICROSECOND 1000

#define PLAYFIELD_ROWS 20
#define PLAYFIELD_COLUMNS 10
#define PLAYFIELD_PLACEMENT_ROW 15
#define PLAYFIELD_PLACEMENT_COLUMN 45
#define PLAYFIELD_SIZE (PLAYFIELD_ROWS * PLAYFIELD_COLUMNS)
#define PLAYFIELD_WINDOW_COLUMNS (PLAYFIELD_COLUMNS * 2)

#define PREVIEW_ROWS 4
#define PREVIEW_COLUMNS 6
#define PREVIEW_PLACEMENT_ROW 25
#define PREVIEW_PLACEMENT_COLUMN 70
#define PREVIEW_WINDOW_COLUMNS (PREVIEW_COLUMNS * 2)

#define WINDOW_BORDER 2

#define TETRIMINO_COUNT 7
#define SQUARES_PER_TETRIMINO 4

#define LIGHTBLUE_SPAWNPOINT 195
#define DARKBLUE_SPAWNPOINT 184
#define ORANGE_SPAWNPOINT 184
#define YELLOW_SPAWNPOINT 195
#define GREEN_SPAWNPOINT 194
#define RED_SPAWNPOINT 194
#define MAGENTA_SPAWNPOINT 184

#endif

