#ifndef TETRIS_GAME_SETTINGS_H
#define TETRIS_GAME_SETTINGS_H

#define TARGET_FPS 144
#define MICROSECONDS_PER_SECOND 1000000
#define TARGET_FRAME_TIME (MICROSECONDS_PER_SECOND / TARGET_FPS)
#define NANOSECONDS_PER_MICROSECOND 1000

#define PLAYFIELD_ROWS 22
#define PLAYFIELD_COLUMNS 10
#define PLAYFIELD_BUFFER_ROWS 2
#define PLAYFIELD_WINDOW_ROWS (PLAYFIELD_ROWS - PLAYFIELD_BUFFER_ROWS)
#define PLAYFIELD_WINDOW_COLUMNS (PLAYFIELD_COLUMNS * 2)
#define PLAYFIELD_SIZE (PLAYFIELD_ROWS * PLAYFIELD_COLUMNS)
#define PLAYFIELD_WINDOW_SIZE (PLAYFIELD_WINDOW_ROWS * PLAYFIELD_COLUMNS)
#define PLAYFIELD_PLACEMENT_ROW 15
#define PLAYFIELD_PLACEMENT_COLUMN 45

#define SCORE_ROWS 1
#define SCORE_COLUMNS 9
#define SCORE_PLACEMENT_ROW 15
#define SCORE_PLACEMENT_COLUMN 70

#define LINES_ROWS 1
#define LINES_COLUMNS 9
#define LINES_PLACEMENT_ROW 18
#define LINES_PLACEMENT_COLUMN 70

#define PREVIEW_ROWS 4
#define PREVIEW_COLUMNS 5
#define PREVIEW_WINDOW_COLUMNS (PREVIEW_COLUMNS * 2)
#define PREVIEW_PLACEMENT_ROW 21
#define PREVIEW_PLACEMENT_COLUMN 70

#define LEVEL_ROWS 1
#define LEVEL_COLUMNS 7
#define LEVEL_PLACEMENT_ROW 27
#define LEVEL_PLACEMENT_COLUMN 70

#define WINDOW_BORDER 2

#define TETRIMINO_COUNT 7
#define SQUARES_PER_TETRIMINO 4

#define LIGHTBLUE_SPAWNPOINT 195
#define DARKBLUE_SPAWNPOINT 184
#define ORANGE_SPAWNPOINT 184
#define YELLOW_SPAWNPOINT 195
#define GREEN_SPAWNPOINT 194
#define RED_SPAWNPOINT 194
#define MAGENTA_SPAWNPOINT 184

#endif

